import { Story, Meta } from '@storybook/react';
import { AutocompleteProps } from '.';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Playground: Story<AutocompleteProps>;
export declare const WithPlaceholder: Story<AutocompleteProps>;
export declare const WithHelperText: Story<AutocompleteProps>;
export declare const HasSuccess: Story<AutocompleteProps>;
export declare const HasError: Story<AutocompleteProps>;
export declare const Required: Story<AutocompleteProps>;
export declare const ReadOnly: Story<AutocompleteProps>;
export declare const Disabled: Story<AutocompleteProps>;
