import { Story, Meta } from '@storybook/react';
import { MenuItemProps } from '.';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Playground: Story<MenuItemProps>;
export declare const Submenu: Story<MenuItemProps>;
export declare const Title: Story<MenuItemProps>;
export declare const Activated: Story<MenuItemProps>;
export declare const Selected: Story<MenuItemProps>;
export declare const Disabled: Story<MenuItemProps>;
