import { Story, Meta } from '@storybook/react';
import { ChipProps } from '.';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Playground: Story<ChipProps>;
export declare const WithIcon: Story<ChipProps>;
export declare const WithAvatar: Story<ChipProps>;
export declare const Disabled: Story<ChipProps>;
export declare const Selected: Story<ChipProps>;
export declare const Custom: Story<ChipProps>;
export declare const Sizes: Story<ChipProps>;
