import { Story, Meta } from '@storybook/react';
import { ImageProps } from '.';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Playground: Story<ImageProps>;
export declare const Highlight: Story<ImageProps>;
export declare const WithFade: Story<ImageProps>;
export declare const WithFallback: Story<ImageProps>;
export declare const WithComponent: Story<ImageProps>;
export declare const WithBorder: Story<ImageProps>;
