import { Story, Meta } from '@storybook/react';
import { TextFieldProps } from '.';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Playground: Story<TextFieldProps>;
export declare const Size: Story<TextFieldProps>;
export declare const HelperText: Story<TextFieldProps>;
export declare const Feedback: Story<TextFieldProps>;
export declare const ReadOnly: Story<TextFieldProps>;
export declare const Required: Story<TextFieldProps>;
export declare const Disabled: Story<TextFieldProps>;
export declare const Type: Story<TextFieldProps>;
export declare const ActionIcon: Story<TextFieldProps>;
export declare const ActionImage: Story<TextFieldProps>;
